#!/usr/bin/env bash
# ============================================================
# Nora — First-time .env generator
# ============================================================
# Usage:  bash setup.sh
#
# Generates a .env file with auto-generated cryptographic secrets
# and working defaults for Docker Compose development.
# ============================================================

set -euo pipefail

ENV_FILE=".env"
EXAMPLE_FILE=".env.example"

# ── Color helpers ────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()  { printf "${CYAN}[info]${NC}  %s\n" "$1"; }
ok()    { printf "${GREEN}[ok]${NC}    %s\n" "$1"; }
warn()  { printf "${YELLOW}[warn]${NC}  %s\n" "$1"; }
error() { printf "${RED}[error]${NC} %s\n" "$1"; }

# ── Pre-flight checks ───────────────────────────────────────

if [ -f "$ENV_FILE" ]; then
  warn ".env already exists."
  printf "  Overwrite? [y/N] "
  read -r answer
  if [[ ! "$answer" =~ ^[Yy]$ ]]; then
    info "Keeping existing .env — no changes made."
    exit 0
  fi
fi

if ! command -v openssl &>/dev/null; then
  error "openssl is required but not found. Install it and re-run."
  exit 1
fi

# ── Generate secrets ─────────────────────────────────────────

info "Generating cryptographic secrets..."

JWT_SECRET=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)
NEXTAUTH_SECRET=$(openssl rand -hex 32)

ok "JWT_SECRET      generated (64-char hex)"
ok "ENCRYPTION_KEY  generated (64-char hex — AES-256-GCM)"
ok "NEXTAUTH_SECRET generated (64-char hex)"

# ── NemoClaw / NVIDIA (optional) ─────────────────────────────

NEMOCLAW_ENABLED="false"
NVIDIA_API_KEY=""

echo ""
printf "${CYAN}[info]${NC}  Platform Mode:\n"
printf "  1) Self-hosted (default) — users pick vCPU/RAM/disk within operator limits\n"
printf "  2) PaaS — Stripe billing with plan-locked resources\n"
printf "  Select [1/2]: "
read -r mode_answer
if [[ "$mode_answer" == "2" ]]; then
  PLATFORM_MODE="paas"
  ok "PaaS mode enabled — configure Stripe keys in .env"
else
  PLATFORM_MODE="selfhosted"
  printf "  Max vCPU per agent [16]: "
  read -r max_vcpu_input
  MAX_VCPU="${max_vcpu_input:-16}"
  printf "  Max RAM (MB) per agent [32768]: "
  read -r max_ram_input
  MAX_RAM_MB="${max_ram_input:-32768}"
  printf "  Max Disk (GB) per agent [500]: "
  read -r max_disk_input
  MAX_DISK_GB="${max_disk_input:-500}"
  printf "  Max agents per user [50]: "
  read -r max_agents_input
  MAX_AGENTS="${max_agents_input:-50}"
  ok "Self-hosted mode — limits: ${MAX_VCPU} vCPU, ${MAX_RAM_MB}MB RAM, ${MAX_DISK_GB}GB disk, ${MAX_AGENTS} agents"
fi

echo ""
printf "${CYAN}[info]${NC}  Enable NVIDIA NemoClaw sandboxed agents? (Requires NVIDIA API key from build.nvidia.com)\n"
printf "  Enable NemoClaw? [y/N] "
read -r nemoclaw_answer
if [[ "$nemoclaw_answer" =~ ^[Yy]$ ]]; then
  NEMOCLAW_ENABLED="true"
  printf "  NVIDIA API key (from build.nvidia.com): "
  read -r nvidia_key
  if [ -n "$nvidia_key" ]; then
    NVIDIA_API_KEY="$nvidia_key"
    ok "NemoClaw enabled with NVIDIA API key"
  else
    warn "NemoClaw enabled but no API key provided — add NVIDIA_API_KEY to .env later"
  fi
else
  info "NemoClaw disabled (can be enabled later in .env)"
fi

# ── Write .env ───────────────────────────────────────────────

info "Writing $ENV_FILE..."

cat > "$ENV_FILE" <<EOF
# ============================================================
# Nora — Environment Configuration
# ============================================================
# Auto-generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ============================================================

# ── Required (auto-generated) ────────────────────────────────
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# ── Database (defaults work with Docker Compose) ─────────────
DB_HOST=postgres
DB_USER=platform
DB_PASSWORD=platform
DB_NAME=platform
DB_PORT=5432

# ── Redis (defaults work with Docker Compose) ────────────────
REDIS_HOST=redis
REDIS_PORT=6379
PORT=4000

# ── OAuth (optional — leave blank to disable) ────────────────
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=http://localhost:8080

# ── Billing (disabled by default) ────────────────────────────
# Set to 'true' to enable plan limits and Stripe integration.
# When false, all users get unlimited agent deployments.
BILLING_ENABLED=false

# ── Platform Mode ────────────────────────────────────────────
PLATFORM_MODE=${PLATFORM_MODE}

# ── Self-hosted limits (only when PLATFORM_MODE=selfhosted) ──
MAX_VCPU=${MAX_VCPU:-16}
MAX_RAM_MB=${MAX_RAM_MB:-32768}
MAX_DISK_GB=${MAX_DISK_GB:-500}
MAX_AGENTS=${MAX_AGENTS:-50}

# ── Stripe (only when PLATFORM_MODE=paas) ────────────────────
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
STRIPE_PRICE_PRO=
STRIPE_PRICE_ENTERPRISE=

# ── Provisioner: docker | proxmox | k8s ──────────────────────
PROVISIONER_BACKEND=docker

# ── Proxmox (only when PROVISIONER_BACKEND=proxmox) ──────────
# PROXMOX_API_URL=
# PROXMOX_TOKEN_ID=
# PROXMOX_TOKEN_SECRET=
# PROXMOX_NODE=pve
# PROXMOX_TEMPLATE=ubuntu-22.04-standard

# ── Security ─────────────────────────────────────────────────
CORS_ORIGINS=http://localhost:8080

# ── LLM Key Storage: database (default) | env ───────────────
KEY_STORAGE=database

# ── Backups & TLS (optional) ─────────────────────────────────
# TLS_CERT_PATH=
# TLS_KEY_PATH=
# AWS_S3_BUCKET=
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=

# ── NemoClaw / NVIDIA (optional) ─────────────────────────────
NEMOCLAW_ENABLED=${NEMOCLAW_ENABLED}
NVIDIA_API_KEY=${NVIDIA_API_KEY}
NEMOCLAW_DEFAULT_MODEL=nvidia/nemotron-3-super-120b-a12b
NEMOCLAW_SANDBOX_IMAGE=ghcr.io/nvidia/openshell-community/sandboxes/openclaw
EOF

ok ".env created successfully"

# ── Summary ──────────────────────────────────────────────────

echo ""
echo "┌──────────────────────────────────────────────────┐"
echo "│       🦞  Nora — Environment Ready               │"
echo "├──────────────────────────────────────────────────┤"
echo "│  Secrets:   auto-generated (JWT, AES, NextAuth)  │"
echo "│  Database:  postgres (Docker Compose default)    │"
echo "│  Redis:     redis (Docker Compose default)       │"
if [ "$PLATFORM_MODE" = "paas" ]; then
echo "│  Mode:      PaaS (Stripe billing)                │"
echo "│  Billing:   DISABLED (set BILLING_ENABLED=true)  │"
else
echo "│  Mode:      Self-hosted (operator limits)        │"
echo "│  Limits:    ${MAX_VCPU:-16}vCPU / ${MAX_RAM_MB:-32768}MB / ${MAX_DISK_GB:-500}GB / ${MAX_AGENTS:-50} agents │"
fi
if [ "$NEMOCLAW_ENABLED" = "true" ]; then
echo "│  NemoClaw:  ENABLED  (NVIDIA Nemotron inference) │"
else
echo "│  NemoClaw:  DISABLED (set NEMOCLAW_ENABLED=true) │"
fi
echo "│  OAuth:     not configured (optional)            │"
echo "│  Stripe:    not configured (optional)            │"
echo "├──────────────────────────────────────────────────┤"
echo "│  Next steps:                                     │"
echo "│    docker compose up                             │"
echo "│    open http://localhost:8080                     │"
echo "└──────────────────────────────────────────────────┘"
echo ""
